spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost}:${POSTGRES_PORT:5432}/poc
    username: sa
    password: test
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  level:
    liquibase: INFO
    org.springframework.boot.autoconfigure.liquibase: DEBUG


liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml
  enabled: true