version: '1'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: test
      POSTGRES_DB: poc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tags-poc

volumes:
  postgres_data:

networks:
  tags-poc:
    driver: bridge