version: '1'

services:
  postgres:
    image: postgres:latest
    container_name: scala_last_write_wins
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: test
      POSTGRES_DB: poc
    ports:
      - "5432:5432"
    volumes:
      - poc_last_write_wins_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - scala-last-write-wins-poc

volumes:
  poc_last_write_wins_data:

networks:
  scala-last-write-wins-poc:
    driver: bridge